import type { Metadata } from "next";
import "./styles/globals.css";


export const metadata: Metadata = {
  title: "Market Aquatic Plants",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <p>aqui es desde layout principal</p>
        {children}
      </body>
    </html>
  );
}
